//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Menu
    {
        public int prato_id { get; set; }
        public int restaurante_id { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [RegularExpression(@"([A-Za-zç0-9á-úÁ-ÚãõêàÀ]*\ ?[A-Za-zç0-9á-úÁ-ÚãõêàÀ]+)+", ErrorMessage = "Caracteres permitidos: letras, números e espaço.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Digite pelo menos 1 caracter e no máximo 50.")]
        public string prato_name { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "Apenas números inteiros - (erro na escrita do banco)")]
        public double preco { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
    }

    public class Menu_view
    {
        public int prato_id;
        public string restaurante_name;
        public string prato_name;
        public double preco;
    }
}
