//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int prato_id { get; set; }
        public int restaurante_id { get; set; }
        public string prato_name { get; set; }
        public double preco { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
    }
}
